name: Moovie
author:
    - Colin Aarts
    - Nathan Bishop
category: Media
tags: [media, video, html5, playlist]
#docs: https://github.com/nbish11/Moovie/wiki
#demo: https://github.io/nbish11/Moovie
#current: 0.1.0